import { Router } from 'express';
const router = Router();
const PLAYLIST_URL='https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8'; const CACHE_TTL_MS=5*60*1000;
interface IptvChannel{id:string;name:string;logo:string;country:string;category:string;tvgId:string;streamUrl:string;type:'hls'|'youtube'|'twitch'|'other'}
let cachedChannels:IptvChannel[]=[];let cachedAt=0;let refreshPromise:Promise<IptvChannel[]>|null=null;
const healthCache=new Map<string,{active:boolean;checkedAt:number}>();
function attr(a:string,k:string){return a.match(new RegExp(`${k}=\"([^\"]*)\"`,'i'))?.[1]?.trim()||''}
function classify(u:string):IptvChannel['type']{const l=u.toLowerCase();if(/\.m3u8(?:$|\?)/i.test(l))return'hls';if(l.includes('youtube.com/')||l.includes('youtu.be/'))return'youtube';if(l.includes('twitch.tv/'))return'twitch';return'other'}
function stableId(n:string,u:string){let h=2166136261;for(const c of `${n}|${u}`){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return`iptv-${(h>>>0).toString(16)}`}
function parseM3U(text:string){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out:IptvChannel[]=[];let pending:Omit<IptvChannel,'streamUrl'|'type'|'id'>|null=null;for(const line of lines){if(line.startsWith('#EXTINF:')){const comma=line.indexOf(','),metadata=comma>=0?line.slice(0,comma):line,name=(comma>=0?line.slice(comma+1):attr(metadata,'tvg-name'))||'Unknown channel';pending={name:attr(metadata,'tvg-name')||name.trim(),logo:attr(metadata,'tvg-logo'),country:attr(metadata,'tvg-country'),category:attr(metadata,'group-title'),tvgId:attr(metadata,'tvg-id')};continue}if(line.startsWith('#'))continue;if(!pending||!/^https?:\/\//i.test(line))continue;out.push({...pending,id:stableId(pending.name,line),streamUrl:line,type:classify(line)});pending=null}return out}
async function loadChannels(force=false){const fresh=cachedChannels.length>0&&Date.now()-cachedAt<CACHE_TTL_MS;if(!force&&fresh)return cachedChannels;if(refreshPromise)return refreshPromise;refreshPromise=fetch(PLAYLIST_URL,{headers:{'User-Agent':'Videoplex/1.0 IPTV reader'},signal:AbortSignal.timeout(20000)}).then(async r=>{if(!r.ok)throw new Error(`Playlist returned ${r.status}`);return parseM3U(await r.text())}).then(c=>{cachedChannels=c;cachedAt=Date.now();return c}).finally(()=>{refreshPromise=null});return refreshPromise}
function allowed(u:string){try{const x=new URL(u);return x.protocol==='http:'||x.protocol==='https:'}catch{return false}}
function proxy(req:any,u:string,referer?:string){let url=`${req.protocol}://${req.get('host')}/api/iptv/proxy?url=${encodeURIComponent(u)}`;if(referer&&allowed(referer))url+=`&referer=${encodeURIComponent(referer)}`;return url}
function rewrite(m:string,source:string,req:any){const base=new URL(source);return m.split(/\r?\n/).map(line=>{if(!line.trim())return line;if(line.startsWith('#'))return line.replace(/URI=\"([^\"]+)\"/gi,(_,uri)=>{try{const resolved=new URL(uri,base).toString();return`URI=\"${proxy(req,resolved,source)}\"`}catch{return`URI=\"${uri}\"`}});try{return proxy(req,new URL(line.trim(),base).toString(),source)}catch{return line}}).join('\n')}
async function checkStream(u:string,type:string){const cached=healthCache.get(u);if(cached&&Date.now()-cached.checkedAt<60_000)return cached.active;let active=false;try{const r=await fetch(u,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 Videoplex/1.0','Accept':type==='hls'?'application/vnd.apple.mpegurl,*/*':'*/*'},signal:AbortSignal.timeout(8000)});if(r.ok){if(type==='hls'){const text=(await r.text()).slice(0,200000);active=/#EXTM3U/i.test(text)&&/#EXTINF|#EXT-X-/i.test(text)}else active=true}}catch{}healthCache.set(u,{active,checkedAt:Date.now()});return active}
router.get('/health',async(req,res)=>{const url=String(req.query.url||'');const type=String(req.query.type||'hls');if(!allowed(url))return res.status(400).json({active:false,error:'Invalid stream URL'});const active=await checkStream(url,type);res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','no-store');res.json({active,checkedAt:new Date().toISOString()})});
router.get('/proxy',async(req,res)=>{const target=String(req.query.url||'');const parentReferer=String(req.query.referer||'');if(!allowed(target))return res.status(400).send('Invalid stream URL');if(parentReferer&&!allowed(parentReferer))return res.status(400).send('Invalid referer');try{const targetUrl=new URL(target);const headers:{[key:string]:string}={'User-Agent':'Mozilla/5.0 Videoplex/1.0','Accept':'*/*'};if(parentReferer){headers.Referer=parentReferer;try{headers.Origin=new URL(parentReferer).origin}catch{}}const r=await fetch(target,{redirect:'follow',headers,signal:AbortSignal.timeout(25000)});if(!r.ok)return res.status(r.status).send(`Upstream stream returned ${r.status}`);const ct=r.headers.get('content-type')||'';const finalUrl=r.url||target;if(/\.m3u8(?:$|\?)/i.test(finalUrl)||/\.m3u8(?:$|\?)/i.test(target)||ct.includes('mpegurl')){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/vnd.apple.mpegurl');res.setHeader('Cache-Control','no-store');return res.send(rewrite(await r.text(),finalUrl,req))}const b=Buffer.from(await r.arrayBuffer());res.setHeader('Access-Control-Allow-Origin','*');if(ct)res.setHeader('Content-Type',ct);res.setHeader('Cache-Control','no-store');return res.send(b)}catch(e){console.error('IPTV proxy error:',e);return res.status(502).send('Unable to reach upstream stream')}});
router.get('/channels',async(req,res)=>{try{const all=await loadChannels(req.query.refresh==='1'),q=String(req.query.q||'').trim().toLowerCase(),country=String(req.query.country||'').trim().toLowerCase(),category=String(req.query.category||'').trim().toLowerCase(),type=String(req.query.type||'').trim().toLowerCase();const filtered=all.filter(c=>(!q||`${c.name} ${c.tvgId} ${c.country} ${c.category}`.toLowerCase().includes(q))&&(!country||c.country.toLowerCase()===country)&&(!category||c.category.toLowerCase()===category)&&(!type||c.type===type));const offset=Math.max(0,Number(req.query.offset||0)),limit=Math.min(60,Math.max(1,Number(req.query.limit||24))),items=filtered.slice(offset,offset+limit),countries=[...new Set(all.map(c=>c.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),categories=[...new Set(all.map(c=>c.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b));res.json({items,total:filtered.length,offset,limit,hasMore:offset+items.length<filtered.length,source:PLAYLIST_URL,cachedAt:cachedAt?new Date(cachedAt).toISOString():null,countries,categories})}catch(e){console.error('IPTV playlist error:',e);res.status(502).json({error:'Unable to load the live TV playlist right now.'})}});
export default router;
